// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Models;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20250619161111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultationRelatedToPost", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "ConsultationId")
                        .HasName("PK__Consulta__3FC274B1200A7A13");

                    b.HasIndex("ConsultationId");

                    b.ToTable("ConsultationRelatedToPost", (string)null);
                });

            modelBuilder.Entity("ConsultationTypesOfConsultant", b =>
                {
                    b.Property<int>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationTypeId")
                        .HasColumnType("int");

                    b.HasKey("ConsultantId", "ConsultationTypeId")
                        .HasName("PK__Consulta__502B7AAC0A232FF8");

                    b.HasIndex("ConsultationTypeId");

                    b.ToTable("ConsultationTypesOfConsultant", (string)null);
                });

            modelBuilder.Entity("Web.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ConsultantDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ConsultantLicense")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int?>("Room")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC078050411D");

                    b.ToTable("Consultant");
                });

            modelBuilder.Entity("Web.Models.ConsultationBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsultationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RegisterTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC074E8DAAB5");

                    b.HasIndex("ConsultantId");

                    b.HasIndex("ConsultationTypeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.ToTable("ConsultationBooking");
                });

            modelBuilder.Entity("Web.Models.ConsultationFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ConsultationBookingId")
                        .HasColumnType("int");

                    b.Property<int?>("RatedStar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RatedTime")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC07E87A6B20");

                    b.HasIndex("ConsultationBookingId");

                    b.ToTable("ConsultationFeedback");
                });

            modelBuilder.Entity("Web.Models.ConsultationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Consulta__3214EC07AC7A5DF7");

                    b.ToTable("ConsultationType");
                });

            modelBuilder.Entity("Web.Models.ContentPostType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ContentP__3214EC07159CE329");

                    b.ToTable("ContentPostType");
                });

            modelBuilder.Entity("Web.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("MedicalHistory")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__Customer__3214EC07053A9468");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Web.Models.Faq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Question")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id")
                        .HasName("PK__FAQ__3214EC079BDDC914");

                    b.ToTable("FAQ");
                });

            modelBuilder.Entity("Web.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("PostedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Post__3214EC0704BEE18B");

                    b.HasIndex("ConsultantId");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Web.Models.PostDetail", b =>
                {
                    b.Property<int>("PostDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostDetailId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("PostDetailId")
                        .HasName("PK__PostDeta__AE5570B9C2DEAA20");

                    b.HasIndex("PostId");

                    b.HasIndex("TypeId");

                    b.ToTable("PostDetail");
                });

            modelBuilder.Entity("Web.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC07538083DC");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Web.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("int");

                    b.Property<int?>("Fee")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Room")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Service__3214EC075EF107C6");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Web.Models.ServiceBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AppointmentTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("RegisterTime")
                        .HasColumnType("datetime");

                    b.Property<string>("Result")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceB__3214EC0755A51DA2");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("StatusId");

                    b.ToTable("ServiceBooking");
                });

            modelBuilder.Entity("Web.Models.ServiceFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RatedStar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RatedTime")
                        .HasColumnType("datetime");

                    b.Property<int?>("ServiceBookingId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ServiceF__3214EC07922C8F90");

                    b.HasIndex("ServiceBookingId");

                    b.ToTable("ServiceFeedback");
                });

            modelBuilder.Entity("Web.Models.Slot", b =>
                {
                    b.Property<int>("Slot1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Slot");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Slot1"));

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Slot1")
                        .HasName("PK__Slot__BC7BA94674B44102");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("Web.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("WorkType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Staff__3214EC07765DC564");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Web.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Status");

                    b.HasKey("Id")
                        .HasName("PK__Status__3214EC07FEF251D5");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC070DE6B444");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D1053468BF2D1B")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("Web.Models.WorkSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SlotId")
                        .HasName("PK__WorkSlot__0A124AAF2D75F149");

                    b.HasIndex("Slot");

                    b.HasIndex("UserId");

                    b.ToTable("WorkSlot");
                });

            modelBuilder.Entity("ConsultationRelatedToPost", b =>
                {
                    b.HasOne("Web.Models.ConsultationType", null)
                        .WithMany()
                        .HasForeignKey("ConsultationId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultat__Consu__3E52440B");

                    b.HasOne("Web.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultat__PostI__3D5E1FD2");
                });

            modelBuilder.Entity("ConsultationTypesOfConsultant", b =>
                {
                    b.HasOne("Web.Models.Consultant", null)
                        .WithMany()
                        .HasForeignKey("ConsultantId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultat__Consu__46E78A0C");

                    b.HasOne("Web.Models.ConsultationType", null)
                        .WithMany()
                        .HasForeignKey("ConsultationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Consultat__Consu__47DBAE45");
                });

            modelBuilder.Entity("Web.Models.Consultant", b =>
                {
                    b.HasOne("Web.Models.User", "IdNavigation")
                        .WithOne("Consultant")
                        .HasForeignKey("Web.Models.Consultant", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Consultant__Id__300424B4");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Web.Models.ConsultationBooking", b =>
                {
                    b.HasOne("Web.Models.Consultant", "Consultant")
                        .WithMany("ConsultationBookings")
                        .HasForeignKey("ConsultantId")
                        .HasConstraintName("FK__Consultat__Consu__4F7CD00D");

                    b.HasOne("Web.Models.ConsultationType", "ConsultationType")
                        .WithMany("ConsultationBookings")
                        .HasForeignKey("ConsultationTypeId")
                        .HasConstraintName("FK__Consultat__Consu__5070F446");

                    b.HasOne("Web.Models.Customer", "Customer")
                        .WithMany("ConsultationBookings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Consultat__Custo__4E88ABD4");

                    b.HasOne("Web.Models.Status", "Status")
                        .WithMany("ConsultationBookings")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__Consultat__Statu__5165187F");

                    b.Navigation("Consultant");

                    b.Navigation("ConsultationType");

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Web.Models.ConsultationFeedback", b =>
                {
                    b.HasOne("Web.Models.ConsultationBooking", "ConsultationBooking")
                        .WithMany("ConsultationFeedbacks")
                        .HasForeignKey("ConsultationBookingId")
                        .HasConstraintName("FK__Consultat__Consu__5BE2A6F2");

                    b.Navigation("ConsultationBooking");
                });

            modelBuilder.Entity("Web.Models.Customer", b =>
                {
                    b.HasOne("Web.Models.User", "IdNavigation")
                        .WithOne("Customer")
                        .HasForeignKey("Web.Models.Customer", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Customer__Id__2D27B809");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Web.Models.Post", b =>
                {
                    b.HasOne("Web.Models.User", "Consultant")
                        .WithMany("Posts")
                        .HasForeignKey("ConsultantId")
                        .HasConstraintName("FK__Post__Consultant__38996AB5");

                    b.Navigation("Consultant");
                });

            modelBuilder.Entity("Web.Models.PostDetail", b =>
                {
                    b.HasOne("Web.Models.Post", "Post")
                        .WithMany("PostDetails")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK__PostDetai__PostI__4316F928");

                    b.HasOne("Web.Models.ContentPostType", "Type")
                        .WithMany("PostDetails")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("FK__PostDetai__TypeI__440B1D61");

                    b.Navigation("Post");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Web.Models.ServiceBooking", b =>
                {
                    b.HasOne("Web.Models.Customer", "Customer")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__ServiceBo__Custo__5441852A");

                    b.HasOne("Web.Models.Service", "Service")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK__ServiceBo__Servi__5535A963");

                    b.HasOne("Web.Models.Status", "Status")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK__ServiceBo__Statu__5629CD9C");

                    b.Navigation("Customer");

                    b.Navigation("Service");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Web.Models.ServiceFeedback", b =>
                {
                    b.HasOne("Web.Models.ServiceBooking", "ServiceBooking")
                        .WithMany("ServiceFeedbacks")
                        .HasForeignKey("ServiceBookingId")
                        .HasConstraintName("FK__ServiceFe__Servi__59063A47");

                    b.Navigation("ServiceBooking");
                });

            modelBuilder.Entity("Web.Models.Staff", b =>
                {
                    b.HasOne("Web.Models.User", "IdNavigation")
                        .WithOne("Staff")
                        .HasForeignKey("Web.Models.Staff", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__Staff__Id__2A4B4B5E");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("Web.Models.User", b =>
                {
                    b.HasOne("Web.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__276EDEB3");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Web.Models.WorkSlot", b =>
                {
                    b.HasOne("Web.Models.Slot", "SlotNavigation")
                        .WithMany("WorkSlots")
                        .HasForeignKey("Slot")
                        .IsRequired()
                        .HasConstraintName("FK__WorkSlot__Slot__35BCFE0A");

                    b.HasOne("Web.Models.User", "User")
                        .WithMany("WorkSlots")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__WorkSlot__UserId__34C8D9D1");

                    b.Navigation("SlotNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web.Models.Consultant", b =>
                {
                    b.Navigation("ConsultationBookings");
                });

            modelBuilder.Entity("Web.Models.ConsultationBooking", b =>
                {
                    b.Navigation("ConsultationFeedbacks");
                });

            modelBuilder.Entity("Web.Models.ConsultationType", b =>
                {
                    b.Navigation("ConsultationBookings");
                });

            modelBuilder.Entity("Web.Models.ContentPostType", b =>
                {
                    b.Navigation("PostDetails");
                });

            modelBuilder.Entity("Web.Models.Customer", b =>
                {
                    b.Navigation("ConsultationBookings");

                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("Web.Models.Post", b =>
                {
                    b.Navigation("PostDetails");
                });

            modelBuilder.Entity("Web.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Web.Models.Service", b =>
                {
                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("Web.Models.ServiceBooking", b =>
                {
                    b.Navigation("ServiceFeedbacks");
                });

            modelBuilder.Entity("Web.Models.Slot", b =>
                {
                    b.Navigation("WorkSlots");
                });

            modelBuilder.Entity("Web.Models.Status", b =>
                {
                    b.Navigation("ConsultationBookings");

                    b.Navigation("ServiceBookings");
                });

            modelBuilder.Entity("Web.Models.User", b =>
                {
                    b.Navigation("Consultant");

                    b.Navigation("Customer");

                    b.Navigation("Posts");

                    b.Navigation("Staff");

                    b.Navigation("WorkSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
